### ISSUE TITLE
Description and how to use in Readme

### ISSUE THREAD

**Issue by lakid** [MaaniGhaffari/sampling_based_planners#1]
Can you add a description of the package and how to use the Matlab code to the README.md?

Maybe you can add some GIF animations as well (make sure to link to the GitHub raw URL if you host them on GitHub ) :smile: 

I can fork the repo to CAS GitHub after.

**Comment by MaaniGhaffari** [comment]
Done, check it out :)

https://github.com/MaaniGhaffari/sampling_based_planners

**Comment by lakid** [comment]
sweet!

Closed via de68ad91d4a8c4ba1b2a6a0e6bdc49c309d978e1
